CREATE DATABASE RESTAURANT_MANAGEMENT_SYSTEM
USE RESTAURANT_MANAGEMENT_SYSTEM


CREATE TABLE Restaurant(
RestaurantID INT PRIMARY KEY,
RestaurantName NVARCHAR(70) NOT NULL
);

CREATE TABLE Branch(
BranchID INT PRIMARY KEY IDENTITY(1,1),
RestaurantID INT FOREIGN KEY REFERENCES Restaurant(RestaurantID),
BranchName NVARCHAR(70) NOT NULL,

BranchSales DECIMAL(12,2) DEFAULT(0) NOT NULL
CONSTRAINT CHECK_BranchSales CHECK (BranchSales >= 0) 
);

CREATE TABLE Staff(
StaffID INT PRIMARY KEY IDENTITY(1,1),
BranchID INT FOREIGN KEY REFERENCES Branch(BranchID),
Name NVARCHAR(70) NOT NULL,

Phone NVARCHAR(20) 
CONSTRAINT CHECK_StaffPhone CHECK (PHONE NOT LIKE '%[^0-9]%'),

Salary DECIMAL (8,2) 
CONSTRAINT CHECK_StaffSalary CHECK (Salary > 35000),

Role NVARCHAR(30)
CONSTRAINT CHECK_StaffRole CHECK (Role IN ('Admin', 'Manager', 'Employee')),


Designation NVARCHAR(70)
CONSTRAINT CHECK_StaffDesignation  CHECK (Designation IN ('Chef', 'Waiter', 'Helper')),

Username NVARCHAR(70) UNIQUE,
Password NVARCHAR(70) 
)


CREATE TABLE Customer(
CustomerID INT PRIMARY KEY IDENTITY(1,1),
Name NVARCHAR(70) NOT NULL,

Phone NVARCHAR(20) 
CONSTRAINT CHECK_CustomerPhone CHECK (PHONE NOT LIKE '%[^0-9]%'),

JoinDate DATE DEFAULT (GETDATE())
)

CREATE BranchCustomer(
BranchID INT FOREIGN KEY REFERENCES Branch(BranchID),
CustomerID INT FOREIGN KEY REFERENCE Customer(CustomerID),
PRIMARY KEY (BranchID, CustomerID)
)